// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagement.API.Data;

#nullable disable

namespace TaskManagement.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskManagement.API.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Priority");

                    b.HasIndex("Status");

                    b.ToTable("Tasks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedTo = "Priya Sharma",
                            CreatedDate = new DateTime(2026, 6, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Configure GitHub Actions for build and test automation on every pull request.",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 6, 18, 14, 30, 0, 0, DateTimeKind.Utc),
                            Priority = "High",
                            Status = "Done",
                            Title = "Set up CI/CD pipeline"
                        },
                        new
                        {
                            Id = 2,
                            AssignedTo = "Marcus Chen",
                            CreatedDate = new DateTime(2026, 6, 12, 10, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Model the core entities and relationships for the task management system.",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 6, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "Critical",
                            Status = "Done",
                            Title = "Design database schema"
                        },
                        new
                        {
                            Id = 3,
                            AssignedTo = "Marcus Chen",
                            CreatedDate = new DateTime(2026, 7, 1, 8, 45, 0, 0, DateTimeKind.Utc),
                            Description = "Add JWT-based authentication to protect API endpoints.",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 8, 5, 11, 20, 0, 0, DateTimeKind.Utc),
                            Priority = "High",
                            Status = "InProgress",
                            Title = "Implement authentication middleware"
                        },
                        new
                        {
                            Id = 4,
                            AssignedTo = "Priya Sharma",
                            CreatedDate = new DateTime(2026, 7, 3, 9, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Support filtering tasks by status and priority via query parameters.",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 15, 13, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "Medium",
                            Status = "Done",
                            Title = "Build task filtering API"
                        },
                        new
                        {
                            Id = 5,
                            AssignedTo = "Elena Rodriguez",
                            CreatedDate = new DateTime(2026, 7, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Display tasks in a table with sortable columns.",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 8, 10, 15, 45, 0, 0, DateTimeKind.Utc),
                            Priority = "Medium",
                            Status = "InProgress",
                            Title = "Create React task list UI"
                        },
                        new
                        {
                            Id = 6,
                            AssignedTo = "Sam O'Neill",
                            CreatedDate = new DateTime(2026, 7, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cover filtering, sorting, and soft delete logic.",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 7, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "Medium",
                            Status = "ToDo",
                            Title = "Write unit tests for TaskService"
                        },
                        new
                        {
                            Id = 7,
                            AssignedTo = "Marcus Chen",
                            CreatedDate = new DateTime(2026, 7, 22, 11, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Return consistent error responses across all endpoints.",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 8, 1, 9, 30, 0, 0, DateTimeKind.Utc),
                            Priority = "High",
                            Status = "Done",
                            Title = "Add global exception handling"
                        },
                        new
                        {
                            Id = 8,
                            AssignedTo = "Elena Rodriguez",
                            CreatedDate = new DateTime(2026, 8, 2, 13, 40, 0, 0, DateTimeKind.Utc),
                            Description = "Priority badges do not match the design spec on the task cards.",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 8, 2, 13, 40, 0, 0, DateTimeKind.Utc),
                            Priority = "Low",
                            Status = "ToDo",
                            Title = "Fix priority badge colors"
                        },
                        new
                        {
                            Id = 9,
                            AssignedTo = "Priya Sharma",
                            CreatedDate = new DateTime(2026, 8, 5, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Investigate slow response times on the task summary endpoint under load.",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 8, 15, 17, 10, 0, 0, DateTimeKind.Utc),
                            Priority = "Critical",
                            Status = "InProgress",
                            Title = "Optimize summary query performance"
                        },
                        new
                        {
                            Id = 10,
                            AssignedTo = "Sam O'Neill",
                            CreatedDate = new DateTime(2026, 8, 8, 10, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Bundle the API, frontend, and SQL Server into a single Compose file.",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 8, 8, 10, 30, 0, 0, DateTimeKind.Utc),
                            Priority = "Medium",
                            Status = "ToDo",
                            Title = "Set up Docker Compose for local dev"
                        },
                        new
                        {
                            Id = 11,
                            AssignedTo = "Elena Rodriguez",
                            CreatedDate = new DateTime(2026, 8, 12, 9, 20, 0, 0, DateTimeKind.Utc),
                            Description = "Ensure Swagger annotations accurately describe all endpoints.",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 8, 12, 9, 20, 0, 0, DateTimeKind.Utc),
                            Priority = "Low",
                            Status = "ToDo",
                            Title = "Review API documentation"
                        },
                        new
                        {
                            Id = 12,
                            AssignedTo = "Marcus Chen",
                            CreatedDate = new DateTime(2026, 8, 14, 14, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gather feedback on the last two-week sprint and identify improvements.",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 8, 16, 10, 5, 0, 0, DateTimeKind.Utc),
                            Priority = "Low",
                            Status = "Done",
                            Title = "Plan sprint retrospective"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
